[tox]
envlist = py314
requires = tox >= 4.0

[testenv]
description = Run unit tests and produce coverage XML
deps = .[dev]
skipsdist = True
commands =
    pip install -e .[dev]
    coverage run -m pytest tests/unit/ --junitxml=pytest-report.xml -q
    coverage xml -o coverage.xml
    coverage html -d coverage_html
    coverage report --fail-under=95
